# @package _global_

optimizer:
  type: AdamW
  lr: 1.0e-3
  weight_decay: 1.0e-4

scheduler:
  type: CosineAnnealingLR
  T_max: 10

trainer:
  max_epochs: 10
  # max_steps: 1000
  # gradient_clip_val: 1.0
