# Refer to
# - https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/
# - https://hydra.cc/docs/patterns/configuring_experiments/
# for more information about config group defaults
defaults:
  - datasets: cifar10
  - models: resnet18.yaml
  - schedules: 10e

trainer:
  # num_nodes: 1
  devices: 4
  accelerator: gpu
  strategy: ddp  # bagua
  precision: 16

  # callbacks:
  #   EarlyStopping(monitor="val_accuracy", min_delta=0.00, patience=3, verbose=False, mode="max")

  # check_val_every_n_epoch: 1
  # limit_train_batches: 10  # shorten the epoch length for debugging
  # limit_val_batches: 5
  # profiler: simple  # advanced, profiling measures the time consuming of all components
