# Refer to Hydra documentation for more information about config group defaults.
# - https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/
# - https://hydra.cc/docs/patterns/configuring_experiments/
defaults:
  - datasets: cifar10
  - models: resnet50
  - schedules: 10e
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y%m%d-%H%M%S}

trainer:  # refer to https://lightning.ai/docs/pytorch/stable/common/trainer.html
  devices: 4
  precision: 16-mixed
  sync_batchnorm: True
  # enable_progress_bar: False  # will log to console and save to file (customized in build_callbacks())
  # profiler: simple
