# @package _global_

data:
  datasets:
    type: CIFAR100
    splits:
      train:
        train: True
      test:
        train: False
    root: datasets/cifar-100
    download: True
  loader:
    batch_size: 32
    num_workers: 4

model:
  num_classes: 100
evaluator:
  type: Accuracy
  task: multiclass
  num_classes: 100
