# @package _global_

data:
  datasets:
    type: CIFAR10
    splits:
      train:
        train: True
      test:
        train: False
    root: data/cifar-10
    download: True
  loader:
    batch_size: 32
    num_workers: 4

model:
  num_classes: 10

evaluator:
  type: Accuracy
  task: multiclass
  num_classes: 10
