# @package _global_

data:
  datasets:
    type: MNIST
    splits:
      train:
        train: True
      test:
        train: False
    root: data/mnist
    download: True
  loader:
    batch_size: 32
    num_workers: 4

model:
  num_classes: 10

evaluator:
  type: MulticlassAccuracy
  num_classes: 10
