# @package _global_

data:
  datasets:
    type: MNIST
    splits:
      train:
        download: True
      test:
        train: False
    root: datasets/mnist
    download: True
  loader:
    batch_size: 32
    num_workers: 4

model:
  num_classes: 10

evaluator:
  type: Accuracy
  task: multiclass
  num_classes: 10
